/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import DTOs.FuncionGuardarDTO;
import Negocio.IFuncionNegocio;
import Negocio.IPeliculaNegocio;
import Negocio.ISalaNegocio;
import Negocio.NegocioException;
import Negocio.PeliculaNegocio;
import com.github.lgooddatepicker.components.DatePicker;
import java.time.LocalTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eduar
 */
public class FrmNuevaFuncion extends javax.swing.JFrame {

    IFuncionNegocio funcionNegocio;
    FrmModificarFuncion modificarFuncion;
    IPeliculaNegocio peliculaNegocio;
    ISalaNegocio salaNegocio;
    
    /**
     * Creates new form FrmAgregarFuncion
     */
    public FrmNuevaFuncion(FrmModificarFuncion modificarFuncion, IFuncionNegocio funcionNegocio, IPeliculaNegocio peliculaNegocio, ISalaNegocio salaNegocio) {
        initComponents();
        
        this.funcionNegocio = funcionNegocio;
        this.modificarFuncion = modificarFuncion;
        this.peliculaNegocio = peliculaNegocio;
        this.salaNegocio = salaNegocio;
        
        try {
            cargarPeliculas();
        } catch (NegocioException ex) {
            Logger.getLogger(FrmNuevaFuncion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            cargarSalas();
        } catch (NegocioException ex) {
            Logger.getLogger(FrmNuevaFuncion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    
    private void cargarPeliculas() throws NegocioException {
            
        try {
            List<String> peliculas = peliculaNegocio.obtenerPeliculas();
            for (String pelicula : peliculas) {
                cbcPelicula.addItem(pelicula);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar las peliculas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void cargarSalas() throws NegocioException {
            
        try {
            List<String> salas = salaNegocio.obtenerSalas();
            for (String sala : salas) {
                cbcSala.addItem(sala);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar las salas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrecio = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblFuncion = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        campoTextoPrecio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cbcPelicula = new javax.swing.JComboBox<>();
        lblPelicula = new javax.swing.JLabel();
        lblHoraInicio = new javax.swing.JLabel();
        cbcSala = new javax.swing.JComboBox<>();
        lblHoraFinal = new javax.swing.JLabel();
        campoTextoDuracionFinal = new javax.swing.JTextField();
        timePickerHoraInicio = new com.github.lgooddatepicker.components.TimePicker();
        btnCalcularHoraFinal = new javax.swing.JButton();
        cbcDias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPrecio.setText("Precio");
        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lblSala.setText("Sala");
        lblSala.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lblDia.setText("Dia");
        lblDia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lblFuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncion.setText("Agregar Función");
        lblFuncion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblFuncion)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnRegresar.setBackground(new java.awt.Color(8, 148, 249));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        campoTextoPrecio.setBackground(new java.awt.Color(136, 201, 239));

        btnGuardar.setBackground(new java.awt.Color(51, 255, 51));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cbcPelicula.setBackground(new java.awt.Color(136, 201, 239));
        cbcPelicula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbcPeliculaItemStateChanged(evt);
            }
        });

        lblPelicula.setText("Pelicula");
        lblPelicula.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lblHoraInicio.setText("Hora Inicio");
        lblHoraInicio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        cbcSala.setBackground(new java.awt.Color(136, 201, 239));

        lblHoraFinal.setText("Hora Final");
        lblHoraFinal.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        campoTextoDuracionFinal.setEditable(false);
        campoTextoDuracionFinal.setBackground(new java.awt.Color(136, 201, 239));

        timePickerHoraInicio.setBackground(new java.awt.Color(136, 201, 239));
        timePickerHoraInicio.setForeground(new java.awt.Color(0, 0, 0));

        btnCalcularHoraFinal.setText("Calcular");
        btnCalcularHoraFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularHoraFinalActionPerformed(evt);
            }
        });

        cbcDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbcPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timePickerHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbcSala, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRegresar)
                    .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar))
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbcDias, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoTextoDuracionFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcularHoraFinal)
                        .addGap(26, 26, 26))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timePickerHoraInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbcPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoTextoDuracionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCalcularHoraFinal)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbcDias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbcSala, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoTextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnGuardar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        modificarFuncion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        float duracionPelicula;
        
        
        try {
                    
            FuncionGuardarDTO funcionGuardar = new FuncionGuardarDTO();
            duracionPelicula = peliculaNegocio.buscarPorId(cbcPelicula.getSelectedIndex() + 1).getDuracion();
            
            LocalTime empezarFuncion = timePickerHoraInicio.getTime();
            LocalTime terminoFuncion = empezarFuncion.plusMinutes((long) duracionPelicula);
            
        
            funcionGuardar.setDiaFuncion((String) cbcDias.getSelectedItem());
            funcionGuardar.setEmpezaFuncion(java.sql.Time.valueOf(timePickerHoraInicio.getTime()));
            funcionGuardar.setPelicula_id(cbcPelicula.getSelectedIndex() + 1);
            funcionGuardar.setPrecio(Float.valueOf(campoTextoPrecio.getText()));
            funcionGuardar.setSala_id(1);
            
            
            funcionGuardar.setTerminoFuncion(java.sql.Time.valueOf(terminoFuncion));
            
            System.out.println(funcionGuardar.getEmpezaFuncion().toString());
            System.out.println(funcionGuardar.getTerminoFuncion().toString());
            
            funcionNegocio.guardar(funcionGuardar);
            JOptionPane.showMessageDialog(this, "Se añadio la funcion de " + (String) cbcPelicula.getSelectedItem() + " con horario de " + (String) cbcDias.getSelectedItem()+ " " + timePickerHoraInicio.toString() + " a " + campoTextoDuracionFinal.getText());
            modificarFuncion.setVisible(true);
            this.dispose();
            
        } catch (NegocioException ex) {
            Logger.getLogger(FrmNuevaFuncion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       

    }//GEN-LAST:event_btnGuardarActionPerformed

    
    private void cbcPeliculaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbcPeliculaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcPeliculaItemStateChanged

    private void btnCalcularHoraFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularHoraFinalActionPerformed
        // TODO add your handling code here:
        
        float duracionPelicula;
        try {
            duracionPelicula = peliculaNegocio.buscarPorId(cbcPelicula.getSelectedIndex() + 1).getDuracion();
            
            LocalTime empezarFuncion = timePickerHoraInicio.getTime();
            LocalTime terminoFuncion = empezarFuncion.plusMinutes((long) duracionPelicula);
            System.out.println(terminoFuncion.toString());
            
            campoTextoDuracionFinal.setText(terminoFuncion.toString());
            
        } catch (NegocioException ex) {
            Logger.getLogger(FrmNuevaFuncion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnCalcularHoraFinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularHoraFinal;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField campoTextoDuracionFinal;
    private javax.swing.JTextField campoTextoPrecio;
    private javax.swing.JComboBox<String> cbcDias;
    private javax.swing.JComboBox<String> cbcPelicula;
    private javax.swing.JComboBox<String> cbcSala;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblHoraFinal;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSala;
    private com.github.lgooddatepicker.components.TimePicker timePickerHoraInicio;
    // End of variables declaration//GEN-END:variables
}
