/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import DTOs.CiudadDTO;
import DTOs.SalaDTO;
import DTOs.SalaGuardarDTO;
import DTOs.SucursalDTO;
import Negocio.ICiudadNegocio;
import Negocio.ISalaNegocio;
import Negocio.ISucursalNegocio;
import Negocio.NegocioException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eduar
 */
public class FrmNuevaSala extends javax.swing.JFrame {

    FrmModificarSala modificarSala;
    ISalaNegocio salaNegocio;
    ISucursalNegocio sucursalNegocio;
    ICiudadNegocio ciudadNegocio;

    private List<CiudadDTO> listaCiudades;
    private List<SucursalDTO> listaSucursales;

    /**
     * Creates new form FrmNuevaSala
     */
    public FrmNuevaSala(FrmModificarSala modificarSala, ISalaNegocio salaNegocio, ISucursalNegocio sucursalNegocio, ICiudadNegocio ciudadNegocio) {
        this.modificarSala = modificarSala;
        this.salaNegocio = salaNegocio;
        this.sucursalNegocio = sucursalNegocio;
        this.ciudadNegocio = ciudadNegocio;
        initComponents();

        try {
            cargarMetodosIniciales(); // Este método se llamará y ahora cargará correctamente la lista de ciudades
        } catch (NegocioException ex) {
            Logger.getLogger(FrmRegistrarse.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Añadir un ItemListener al JComboBox de cbcCiudad para recargar las sucursales al cambiar de ciudad
        cbcCiudad.addItemListener(e -> {
            if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                try {
                    cargarSucursales(); // Llama al método de cargar sucursales cada vez que se selecciona una nueva ciudad
                } catch (NegocioException ex) {
                    JOptionPane.showMessageDialog(this, "Error al cargar las sucursales: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    private void cargarMetodosIniciales() throws NegocioException {
        cargarCiudades();
        cargarSucursales();
        campoTextoLimpieza.setText("15");
    }

    private void cargarCiudades() throws NegocioException {
        try {
            // Inicializa la lista de ciudades antes de usarla
            listaCiudades = ciudadNegocio.obtenerCiudadesDTO();

            for (CiudadDTO ciudad : listaCiudades) {
                cbcCiudad.addItem(ciudad.getNombre());
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar las ciudades: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarSucursales() throws NegocioException {
        try {
            cbcSucursal.removeAllItems(); // Limpiar las sucursales previas en el JComboBox

            // Obtener el índice seleccionado en el JComboBox de ciudades
            int selectedIndex = cbcCiudad.getSelectedIndex();
            if (selectedIndex < 0) {
                return;
            }

            // Obtener el ID de la ciudad seleccionada utilizando la lista de ciudades
            int idCiudad = listaCiudades.get(selectedIndex).getId();

            // Cargar las sucursales correspondientes a la ciudad seleccionada
            listaSucursales = sucursalNegocio.buscarSucursalPorIdCiudad(idCiudad);

            // Agregar cada sucursal al JComboBox
            for (SucursalDTO sucursal : listaSucursales) {
                cbcSucursal.addItem(sucursal.getNombre());
            }

            JOptionPane.showMessageDialog(this, "Sucursales cargadas correctamente.");
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar las sucursales: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargarSucursales = new javax.swing.JButton();
        lblPelicula = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        cbcSucursal = new javax.swing.JComboBox<>();
        lblSucursal = new javax.swing.JLabel();
        lblHoraFinal = new javax.swing.JLabel();
        campoTextoAsientos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblSala = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        campoTextoPrecio = new javax.swing.JTextField();
        cbcCiudad = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        lblCiudad = new javax.swing.JLabel();
        campoTextoNombre = new javax.swing.JTextField();
        lblLimpieza = new javax.swing.JLabel();
        campoTextoLimpieza = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargarSucursales.setText("Cargar Sucursales");
        btnCargarSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarSucursalesActionPerformed(evt);
            }
        });

        lblPelicula.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblPelicula.setText("Nombre");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblPrecio.setText("Precio");

        cbcSucursal.setBackground(new java.awt.Color(136, 201, 239));

        lblSucursal.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSucursal.setText("Sucursal");

        lblHoraFinal.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblHoraFinal.setText("Asientos disponibles");

        campoTextoAsientos.setBackground(new java.awt.Color(136, 201, 239));

        lblSala.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblSala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSala.setText("Agregar Sala");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblSala)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnRegresar.setText("Regresar");
        btnRegresar.setBackground(new java.awt.Color(8, 148, 249));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        campoTextoPrecio.setBackground(new java.awt.Color(136, 201, 239));

        cbcCiudad.setBackground(new java.awt.Color(136, 201, 239));

        btnGuardar.setText("Guardar");
        btnGuardar.setBackground(new java.awt.Color(51, 255, 51));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblCiudad.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCiudad.setText("Ciudad");

        campoTextoNombre.setBackground(new java.awt.Color(136, 201, 239));

        lblLimpieza.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblLimpieza.setText("Tiempo limpieza");

        campoTextoLimpieza.setEditable(false);
        campoTextoLimpieza.setBackground(new java.awt.Color(136, 201, 239));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbcCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoTextoPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoTextoNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbcSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraFinal)
                            .addComponent(campoTextoLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLimpieza))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnCargarSucursales)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSucursal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarSucursales))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnGuardar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarSucursalesActionPerformed
        // TODO add your handling code here:
        try {
            cbcSucursal.removeAllItems(); // Limpiar las sucursales previas en el JComboBox
            List<String> sucursales = sucursalNegocio.obtenerSucursales();

            for (String sucursal : sucursales) {
                cbcSucursal.addItem(sucursal); // Agregar cada sucursal al JComboBox
            }

            JOptionPane.showMessageDialog(this, "Sucursales cargadas correctamente.");
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar las sucursales: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCargarSucursalesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        modificarSala.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            // Obtener los datos de los campos de texto y ComboBox
            String nombre = campoTextoNombre.getText();
            float precio = Float.parseFloat(campoTextoPrecio.getText());
            int asientosDisponibles = Integer.parseInt(campoTextoAsientos.getText());
            int tiempoLimpieza = Integer.parseInt(campoTextoLimpieza.getText());

            // Obtener el índice seleccionado en el ComboBox de sucursales
            int sucursalIndex = cbcSucursal.getSelectedIndex();
            if (sucursalIndex < 0) {
                JOptionPane.showMessageDialog(this, "Seleccione una sucursal válida.");
                return;
            }

            // Obtener el ID real de la sucursal seleccionada
            int idSucursal = listaSucursales.get(sucursalIndex).getId();

            // Crear el DTO de la sala
            SalaGuardarDTO nuevaSala = new SalaGuardarDTO();
            nuevaSala.setNombre(nombre);
            nuevaSala.setPrecio(precio);
            nuevaSala.setAsientos_disponibles(asientosDisponibles);
            nuevaSala.setMinutosLimpiza(tiempoLimpieza);
            nuevaSala.setSucursa_id(idSucursal); // Usar el ID real de la sucursal

            // Llamar al método de negocio para guardar la sala
            salaNegocio.guardar(nuevaSala);

            JOptionPane.showMessageDialog(this, "Sala guardada correctamente.");

            // Regresar al formulario de modificar sala y cerrar esta ventana
            modificarSala.setVisible(true);
            this.dispose();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar la sala: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese valores numéricos válidos en los campos correspondientes.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarSucursales;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField campoTextoAsientos;
    private javax.swing.JTextField campoTextoLimpieza;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JTextField campoTextoPrecio;
    private javax.swing.JComboBox<String> cbcCiudad;
    private javax.swing.JComboBox<String> cbcSucursal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblHoraFinal;
    private javax.swing.JLabel lblLimpieza;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblSucursal;
    // End of variables declaration//GEN-END:variables
}
